<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PCD4UT7" ignored="3" name="Default test(failed)(failed)" tests="2" failures="1" timestamp="2023-01-06T15:42:08 IST" time="20.875" errors="0">
  <testcase name="Test5" time="0.121" classname="TestCases.FailedTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.Test5(FailedTest.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase name="Test3" time="0.085" classname="TestCases.FailedTest"/>
  <testcase name="Test1" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase name="Test4" time="0.0" classname="TestCases.FailedTest">
    <ignored/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Default test(failed)(failed) -->
